# [M3S02] - Ex. 1 — Separação de X e y

**Objetivo:** separar as variáveis preditoras (X) da variável resposta (y) a partir da base de dados farmacêutica.

**Base de dados:** `dados_AP - [M3S01] - Ex. 1 até [M3S03] - Ex. 4.csv`

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('../../data/input/csv/dados_AP - [M3S01] - Ex. 1 até [M3S03] - Ex. 4.csv')
df.head()

   investimento_marketing  preco_medicamento  mes  demanda
0                   16795                844   11      353
1                    1860                172    5       60
2                   39158                331   12       55
3                   45732                313    1       61
4                   12284                617    2      269

## Separação de X e y

In [8]:
X = df[['investimento_marketing', 'preco_medicamento', 'mes']]
y = df['demanda']

print('Variáveis preditoras (X):')
print(f'  Colunas : {list(X.columns)}')
print(f'  Shape   : {X.shape}')
print()
print('Variável resposta (y):')
print(f'  Coluna  : {y.name}')
print(f'  Shape   : {y.shape}')

Variáveis preditoras (X):
  Colunas : ['investimento_marketing', 'preco_medicamento', 'mes']
  Shape   : (20000, 3)

Variável resposta (y):
  Coluna  : demanda
  Shape   : (20000,)

In [9]:
X.head()

   investimento_marketing  preco_medicamento  mes
0                   16795                844   11
1                    1860                172    5
2                   39158                331   12
3                   45732                313    1
4                   12284                617    2

In [10]:
y.head()

0    353
1     60
2     55
3     61
4    269
Name: demanda, dtype: int64

## Conclusão

A separação de **X** e **y** é o primeiro passo obrigatório antes de treinar qualquer modelo de ML.

| | Variáveis | Tipo |
|---|---|---|
| **X** | `investimento_marketing`, `preco_medicamento`, `mes` | DataFrame (entrada do modelo) |
| **y** | `demanda` | Series (o que o modelo deve prever) |

Essa estrutura é compatível com a API do **scikit-learn**, onde todos os estimadores recebem `model.fit(X, y)`.